### ISSUE TITLE
[Question] Devmoji and Commitizen

### ISSUE THREAD

**Issue by frbrz** [folke/devmoji#32]
Hi. This project is cool. I'm wondering how can I add it to my project.

**Devmoji and Commitizen**

Currently, I have a husky hook which looks like this...:

```json
  "husky": {
    "hooks": {
      "prepare-commit-msg": "yarn run prepare-commit-msg"
    }
  },
```

Inside, prepare-commit-msg runs [commitizen](https://github.com/commitizen/cz-cli#husky) `exec < /dev/tty && git cz --hook || true`.
Does you think it's ok to use both? How would you use devmoji in this situation?

**Devmoji logs**

I would also like to add that when I add devmoji as a dev dependency `yarn add --dev devmoji` and try to run its logs with `yarn devmoji --log` it exits with an error `error Command failed with exit code 1.`. Is this expected behaviour?

**Comment by folke** [comment]
For some reason, I totally missed this very first issue :)

You should be able to add Devmoji like this:
```shell
exec < /dev/tty && git cz --hook && npx --no-install devmoji -e || true
```

I've actually added a `--lint` feature a couple of weeks ago, but forgot to update the documentation.
With this, it will check if the commit message is a conventional commit and will fail otherwise. To it, simply use the following git hook:
```js
"husky": {
    "hooks": {
      "prepare-commit-msg": "npx --no-install devmoji -e --lint"
    }
}
```

`npx devmoji --log` parses standard input, so should be used as:
```shell
$ git log | devmoji --log
```

I'm using a `.gitconfig` alias for a prettier `git log`
```
[alias]
l = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --decorate --date=short
```

Then you can create an alias in your .zshrc or .bashrc like:
```shell
alias gl='g l --color | devmoji --log --color | less -rXF'
```

I hope this helps!

**Comment by frbrz** [comment]
OK. Thanks! 
It was easy. The only thing, is that using it this way: `exec < /dev/tty && git cz --hook && npx --no-install devmoji -e || true` there is no space between the emoji and the commit message:

![Screenshot from 2020-02-29 16-32-01](https://user-images.githubusercontent.com/32760239/75613885-421d2780-5b11-11ea-8be0-8636415d8333.png)

Even if I make sure I add an space inside my editor: 

![Screenshot from 2020-02-29 16-35-34](https://user-images.githubusercontent.com/32760239/75613923-adff9000-5b11-11ea-9394-03803adbeb83.png)
![Screenshot from 2020-02-29 16-36-05](https://user-images.githubusercontent.com/32760239/75613925-afc95380-5b11-11ea-8f55-668e3ebe61de.png)

It's a minor thing, but maybe you want to explore it. 
You can close the issue if you want or use it to track this thing.

**Comment by frbrz** [comment]
About notifications, maybe you want to check this project: [notifier-for-github](https://github.com/sindresorhus/notifier-for-github). It's a FOSS extension for chrome and firefox with web and desktop notifications.

**Comment by folke** [comment]
The space is actually a limitation in rendering unicode symbols in certain terminals. Has something todo with unicode 9 widths.

If you copy a commit message from your terminal and paste it in a text editor, you'll see it's rendered correctly. Same on Github.

In vs-code, the experimental integrated terminal renders it correctly, but iTerm2 does not.

Thanks for the tip on notifier! Using it already :)
