### ISSUE TITLE
devmoji for bots

### ISSUE THREAD

**Issue by kopach** [folke/devmoji#68]
Hi. I do really like this project and already integrated is as a git hook for my personal usage. However, I would like to go further and make all the commits in repo be processed by `devmoji`. There are many commits, which comes from automated tools (e.g. renovate-bot, snyk, etc) in my repos. Is there any recipe to make those tools also use `devmoji`? Or can I somehow post-process commits from bots by devmoji?

**Comment by folke** [comment]
I don't think that's possible unfortunately.

You can't easily update git messages after the fact.

Your best bet is to configure the bot to use a git message as the ones provided by Devmoji.

**Comment by kopach** [comment]
ok, got it, thanks
