### ISSUE TITLE
devmoji type(scope) not blue when using `--log` option

### ISSUE THREAD

**Issue by brandonpittman** [folke/devmoji#81]
I'm using the git log command from the docs and the output is the same, sans the blue text for the `type(scope)` part. Any idea why it might not work when passing it through `git log`?

Just to test, I ran these commands…

```bash
echo "testing feat: ✨ cool stuff" | devmoji # => no coloring
echo "feat: ✨ cool stuff" | devmoji # => HAS coloring
echo "feat: cool stuff" | devmoji --log # => no coloring
```

**Comment by folke** [comment]
Thank you for reporting this!

The option for `--color` was never passed to the method that formats the log using `--log`. Fixed in the new release.

**Comment by brandonpittman** [comment]
@folke Can confirm it's working. Thank you!
