### ISSUE TITLE
refactor and config alignment is off when displayed with devmoji -l

### ISSUE THREAD

**Issue by brandonpittman** [folke/devmoji#86]
https://github.com/folke/devmoji/blob/c7370de7e260156e8c2f97870e6564201658c49c/src/cli.ts#L99-L103

Seems like the above code is handling the logging to terminal *and seems fine*. I'm seeing misaligned text in the CLI listing though.

![CleanShot 2020-12-01 at 10 53 36@2x](https://user-images.githubusercontent.com/967145/100687365-8355a700-33c3-11eb-9317-bb2308e4a8f1.png)

**Comment by folke** [comment]
The miss-alignment is actually a limitation in rendering unicode symbols in certain terminals. Has something todo with unicode 9 widths.

If you copy the `Devmoji` output from your terminal and paste it in a text editor, you'll see it's rendered correctly. Same on Github.

In vs-code, the experimental integrated terminal renders it correctly, but iTerm2 does not by default.

To change the behaviour in iTerm2, you can disable `Use Unicode version 9+ widths`
![image](https://user-images.githubusercontent.com/292349/100712820-3abcd000-3368-11eb-99b1-99602d58b41f.png)

Hope this helps!

**Comment by brandonpittman** [comment]
@folke Thanks!
