### ISSUE TITLE
[compat] Vim Fugitive won't work with pre-commit-msg hook

### ISSUE THREAD

**Issue by brandonpittman** [folke/devmoji#89]
I had an issue where the [vim-fugitive](https://github.com/tpope/vim-fugitive) wasn't working with the `prepare-commit-msg` hook. Simply changing to the `commmit-msg` hook in my Husky config got things working as they used to—it caught bad commit messages.

Am I missing anything by using the `commit-msg` hook instead of `prepare-commit-msg`? If not, it might be worth mentioning that the `commit-msg` hook can be used as well. 🧠

**Comment by folke** [comment]
Nope, you should be good. It's actually better to use `commit-msg` if you also use Devmoji's `--lint` option.

`prepare-commit-msg` needs to be used if you want to use Devmoji in combination with something like [commit-lint](https://commitlint.js.org/#/)

I'll update the docs to reflect this!

**Comment by folke** [comment]
Fixed in https://github.com/folke/devmoji/commit/8f7b36ab0ec7e0623f0e0a597d166749d250912e
